export const projects = [
  {
    type: 'urban technology',
    name: 'mobiladelphia',
    description: `Mobiladelphia is for planners, or anyone with an interest in Philadelphia's mobility, answering questions like: When do people typically go shopping in Chinatown and from where?`,
    year: 2022,
    by: 'Jie Li',
    role: 'Individual',
    titleImageLink: `../assets/thumbnails/mobiladelphia.png`,
    mainLink: `../blog-posts/mobiladelphia.html`,
    githubLink: `https://github.com/Leejere/js-final-project`,
    appLink: `https://mobiladelphia.herokuapp.com/`,
  },
  {
    type: 'urban technology',
    name: 'mobile philly',
    description: `This project produces five blog posts about mobility and some other related topics, using Python's machine-learning and latest interactive visualiztion packages such as <code>altair</code> and <code>holoviz</code>`,
    year: 2022,
    by: 'Jie Li, Jie Wang',
    role: 'Posts 01 to 03',
    titleImageLink: `https://raw.githubusercontent.com/Leejere/mobile-philly/main/assets/gif/destination-by-hour.gif`,
    mainLink: `../blog-posts/mobile-philly.html`,
    githubLink: `https://github.com/Leejere/mobile-philly`,
    appLink: `https://leejere.github.io/mobile-philly/`,
  },
  {
    type: 'urban technology',
    name: `canvassers`,
    description: `A mobile-friendly web-app for voter canvassing. The canvasser can select the voters from a list and map, view their status and other info, and record additional info. Interacts with Firebase`,
    year: 2022,
    by: 'Jie Li, Myron Banez',
    role: 'Most work',
    titleImageLink: `../assets/thumbnails/canvassers.png`,
    mainLink: `../blog-posts/canvassers.html`,
    githubLink: `https://github.com/Leejere/js-voter-canvassing`,
    appLink: `https://leejere.github.io/js-voter-canvassing/site/`,
  },
  {
    type: 'urban technology',
    name: 'LoSIMS',
    description: `Addressing street flooding with a low-cost distributed sensor network in stormwater inlets across Philadelphia. Prototyped with Arduino`,
    year: 2022,
    by: 'Aaron Katz, Jie Li, Zoe Kerrich',
    role: 'Design and diagramming',
    titleImageLink: `../assets/thumbnails/LoSIMS.png`,
    mainLink: `../blog-posts/LoSIMS.html`,
    githubLink: ``,
    appLink: `http://www.sensingthecity.com/losims/`,
  },
  {
    type: 'urban technology',
    name: 'delayed early',
    description: `This project aims to predict train delays for New Jersey Transit using machine learning in R`,
    year: 2021,
    by: 'Jie Li, Xiong Zheng',
    role: 'Data cleaning and model',
    titleImageLink: `../assets/thumbnails/delayed-early.png`,
    mainLink: `../blog-posts/delayed-early.html`,
    githubLink: `https://github.com/Leejere/Predicting-NJ-transit-delays`,
  },
  {
    type: 'urban technology',
    name: 'rebalancing citibike',
    description: `Predicting the trip starts and trip ends across time and space, revealing bike-dock imbalances and inform the manual distribution of bikes for NYC citiBike`,
    year: 2021,
    by: 'Jie Li',
    role: 'Individual',
    titleImageLink: `../assets/thumbnails/citybike-prediction.gif`,
    mainLink: `../blog-posts/citybike-prediction.html`,
    githubLink: `https://github.com/Leejere/predicting-NYC-bikeshare-usage`,
  },
  {
    type: 'planning & design',
    name: 'NRG station TOD',
    description: `Urban design near NRG station, south terminal of Philadelphia'a Broad Street Line. High-density commercial and residential land use with quality public realm`,
    year: 2022,
    by: 'Jie Li, Yan Wang',
    role: 'Design and diagramming',
    titleImageLink: `../assets/thumbnails/nrg-station-tod.png`,
    mainLink: `../blog-posts/nrg-station-tod.html`,
  },
  {
    type: 'planning & design',
    name: 'stabilizing Mantua',
    description: `Site planning to stabilize Mantua in West Philly`,
    year: 2022,
    by: 'Jie Li, Yan Wang',
    role: 'Design and diagramming',
    titleImageLink: `../assets/thumbnails/mantua.png`,
    mainLink: `../blog-posts/stabilizing-mantua.html`,
  },
  {
    type: 'planning & design',
    name: 'miniblocks',
    description: `Site planning for a neighborhood in Grays Ferry, Philadelphia. Used finer gridding to create a more active community`,
    year: 2021,
    by: 'Jie Li, Yan Wang',
    role: 'Design and diagramming',
    titleImageLink: `../assets/thumbnails/miniblocks.png`,
    mainLink: `../blog-posts/miniblocks.html`,
  },
  {
    type: 'planning & design',
    name: 'autonomous Navy Yard',
    description: `Designing for Navy Yard which is pioneering in adapting for the age of autonomous vehicles (public AV fleets). Focused on the gateway and office building concepts`,
    year: 2021,
    by: 'Jie Li (in team of eight)',
    role: 'Individual for work shown here',
    titleImageLink: `../assets/thumbnails/autonomous-navy-yard.png`,
    mainLink: `../blog-posts/autonomous-navy-yard.html`,
  },
  {
    type: 'planning & design',
    name: 'other design drawings',
    description: `Urban design drawings from previous projects earlier than 2021`,
    year: `2020 or earlier`,
    by: 'Jie Li',
    role: 'Individual',
    titleImageLink: `../assets/thumbnails/other-design-drawings.png`,
    mainLink: `../blog-posts/other-design-drawings.html`,
  },
];
