export const projects = [
  {
    type: 'urban technology',
    name: 'mobiladelphia',
    description: `Mobiladelphia is for planners, or anyone with an interest in Philadelphia's mobility, answering questions like: When do people typically go shopping in Chinatown and from where?`,
    year: 2022,
    by: 'Jie Li',
    role: 'Individual',
    titleImageLink: `../assets/thumbnails/mobiladelphia.png`,
    mainLink: `../blog-posts/mobiladelphia.html`,
    githubLink: `https://github.com/Leejere/js-final-project`,
    appLink: `https://mobiladelphia.herokuapp.com/`,
  },
  {
    type: 'urban technology',
    name: 'mobile philly',
    description: `This project produces five blog posts about mobility and some other related topics, using Python's machine-learning and latest interactive visualiztion packages such as <code>altair</code> and <code>holoviz</code>`,
    year: 2022,
    by: 'Jie Li, Jie Wang',
    role: 'Posts 01 to 03',
    titleImageLink: `https://raw.githubusercontent.com/Leejere/mobile-philly/main/assets/gif/destination-by-hour.gif`,
    mainLink: `../blog-posts/mobile-philly.html`,
    githubLink: `https://github.com/Leejere/mobile-philly`,
    appLink: `https://leejere.github.io/mobile-philly/`,
  },
  {
    type: 'urban technology',
    name: 'delayed early',
    description: `This project aims to predict train delays for New Jersey Transit using machine learning in R`,
    year: 2022,
    by: 'Jie Li, Xiong Zheng',
    role: 'Data cleaning and model',
    titleImageLink: `../assets/thumbnails/delayed-early.gif`,
    mainLink: `../blog-posts/delayed-early.html`,
    githubLink: `https://github.com/Leejere/Predicting-NJ-transit-delays`,
  },
];
